In [2]:
import oracledb
import pandas as pd
import hashlib
import numpy as np
import re
from IPython.display import display

In [3]:
# Configura tus credenciales y detalles de conexión
usuario = "evaluacion2" 
contrasena = "123456" 
dsn_tns = "localhost/xe"
# Establece la conexión a la base de datos
try: 
    conexion = oracledb.connect(user=usuario, password=contrasena, dsn=dsn_tns)
    print("¡Conexión exitosa a la base de datos Oracle!")
except Exception as e:
    print(f"Error al conectar: {e}")

¡Conexión exitosa a la base de datos Oracle!

In [4]:
# 1. Extraemos los datos a DataFrames de pandas usando consultas SQL y la conexión establecida
df_clientes = pd.read_sql("SELECT * FROM CLIENTES", con=conexion)

display(df_clientes)

C:\Users\pedro\AppData\Local\Temp\ipykernel_224\87974121.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_clientes = pd.read_sql("SELECT * FROM CLIENTES", con=conexion)

,IDCLIENTE,RUT,NOMBRE,APELLIDOPATERNO,APELLIDOMATERNO,TELEFONO,EMAIL,DIRECCION,CIUDAD,CODIGOPOSTAL,FECHAREGISTRO
0,20863,19.989.450-6,"�lex, Mej�a",NaN,NaN,+56935893171,urpykrpbgk421@mailserver.io,Camino Rivadavia 2430,Pe�aflor,6042,04192012
1,20864,093361490,"Sandra, Estrada, Paredes",NaN,NaN,+56916325993,NaN,Ruta Bol�var 6657,Quillota,8561,17/11/2015
2,20865,647466082,Antonio,Mart�nez,Aguilar,+56998858621,wwpphj287@sample.cl,Calle Moreno 9165 dpto. 1364,San Antonio,2949,2008-10-01
3,20866,22297560-7,Teresa,Montes,NaN,+56992309896,qskeika892@mailserver.io,Camino Independencia 5617,Punta Arenas,2274,2007-11-20
4,20867,000000246317136,Mart�n,NaN,NaN,+56915496531,NaN,Avenida Larra�n 6266,Pe�aflor,8691,17/01/2006
...,...,...,...,...,...,...,...,...,...,...,...
4995,25570,23.053.961-8,Guadalupe,Aguilar,Guti�rrez,+56942106573,ickvmaft488@demo.net,Calle Rivadavia 8983 dpto. 1389,Iquique,8131,2015-08-31
4996,25571,25666348-K,Gerardo,Miranda,NaN,+56925739813,NaN,Calle Sucre 7808,San Felipe,2078,01092020
4997,25572,80.105.9905,Oscar,NaN,NaN,NaN,ucvoldgy316@sample.cl,Calle Yrigoyen 6271 dpto. 1185,La Pintana,7425,2010-11-20
4998,25573,99657518-4,"Gabriela, Soto",NaN,NaN,+56945414243,dqvhcny980@example.com,Ruta Belgrano 3514,Osorno,7830,05102009
4999,25574,70.021.315-8,"Irene, Silva, N��ez",NaN,NaN,NaN,tbrwn652@testmail.org,Ruta Las Heras 1181,San Fernando,8073,04/02/2023

In [5]:
# 2. Filtramos y mostramos SOLO los registros que tienen nulos en cada DataFrame 
print("--- CLIENTES CON DATOS FALTANTES (Nulos) ---")
# df.isnull().any(axis=1) filtra las filas que tienen al menos un NaN en cualquier columna 
clientes_nulos = df_clientes[df_clientes.isnull().any(axis=1)]
display(clientes_nulos)

--- CLIENTES CON DATOS FALTANTES (Nulos) ---

,IDCLIENTE,RUT,NOMBRE,APELLIDOPATERNO,APELLIDOMATERNO,TELEFONO,EMAIL,DIRECCION,CIUDAD,CODIGOPOSTAL,FECHAREGISTRO
0,20863,19.989.450-6,"�lex, Mej�a",NaN,NaN,+56935893171,urpykrpbgk421@mailserver.io,Camino Rivadavia 2430,Pe�aflor,6042,04192012
1,20864,093361490,"Sandra, Estrada, Paredes",NaN,NaN,+56916325993,NaN,Ruta Bol�var 6657,Quillota,8561,17/11/2015
3,20866,22297560-7,Teresa,Montes,NaN,+56992309896,qskeika892@mailserver.io,Camino Independencia 5617,Punta Arenas,2274,2007-11-20
4,20867,000000246317136,Mart�n,NaN,NaN,+56915496531,NaN,Avenida Larra�n 6266,Pe�aflor,8691,17/01/2006
5,20868,27.485.359-4,"Gerardo, Blanco",NaN,NaN,+56910124588,nwnurlnws501@mailserver.io,Avenida Alvear 2324,Buin,4447,06-08-2006
...,...,...,...,...,...,...,...,...,...,...,...
4994,25569,99.304.571-K,"Esteban, Arellano, Padilla",NaN,NaN,+56975630510,zgcpxc993@sample.cl,Camino La Paz 8928,La Serena,1617,29/04/2009
4996,25571,25666348-K,Gerardo,Miranda,NaN,+56925739813,NaN,Calle Sucre 7808,San Felipe,2078,01092020
4997,25572,80.105.9905,Oscar,NaN,NaN,NaN,ucvoldgy316@sample.cl,Calle Yrigoyen 6271 dpto. 1185,La Pintana,7425,2010-11-20
4998,25573,99657518-4,"Gabriela, Soto",NaN,NaN,+56945414243,dqvhcny980@example.com,Ruta Belgrano 3514,Osorno,7830,05102009
4999,25574,70.021.315-8,"Irene, Silva, N��ez",NaN,NaN,NaN,tbrwn652@testmail.org,Ruta Las Heras 1181,San Fernando,8073,04/02/2023